spring:
  profiles: dev
  datasource:
    url: jdbc:mysql:XXX:@XXX:XXX/XXX
    username: XXX
    password: XXX
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect